---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.j.layershift.co.uk/
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=kjhbxwkjnbxwn8u9839282
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=kjhbxwkjnbxwn8u9839282
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=kjhbxwkjnbxwn8u9839282
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: db_pma
    ports:
      - 8081:80
    restart: always
    depends_on:
      - bookstack_db
    environment:
      - PMA_HOST=bookstack_db
      - MYSQL_ROOT_PASSWORD=kjhbxwkjnbxwn8u9839282
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=kjhbxwkjnbxwn8u9839282
      - PMA_USER=bookstack
      - PMA_PASSWORD=kjhbxwkjnbxwn8u9839282
